ridafkih/schemix

- lib/@types/prisma-generator.ts
- lib/index.ts
- lib/modules/PrismaScalarField.ts
- lib/modules/PrismaSchema.ts
- lib/util/blocks.ts
I have a requirement to use https://github.com/notiz-dev/prisma-dbml-generator with our schema; this PR attempts to add support for multiple generator configs, with arbitrary values to hopefully open up the config to any generator someone may want to add.
> feat: support multiple generators

- README.md
`yarn install schemix` gives an error for newer version of yarn :
```
error `install` has been replaced with `add` to add new dependencies. Run "yarn add schemix" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This PR aims to fix it in the docs !
> Updated yarn instructions

- example/models/Post.model.ts
- example/models/User.model.ts
- example/schema.prisma
- lib/@types/prisma-type-options.ts
- lib/modules/PrismaModel.ts
- lib/util/options.ts
Addresses issue #12 and adds the ability to add composite IDs. 
```ts
export default createModel((UserModel) => {
UserModel
.mixin(DateTimeMixin)
.relation("posts", PostModel, { list: true })
.relation("friends", UserModel, { list: true, name: "friends" })
.relation("friendRelations", UserModel, { list: true, name: "friends" })
.string("email")
.string("fullName")
.id({ fields: ["email"] });
})
```
> add `PrismaModel#id` method to add @@id fields.

- example/README.md
- example/models/User.model.ts
- example/models/auth/Auth.model.ts
- example/schema.prisma
- lib/util/import.ts
This PR supports putting enums / mixins / models in nested folders. This is particularly helpful to separate the models by domain folders:
```
- models
- auth
- Account.model.ts
- VerificationToken.model.ts
- order
- Order.model.ts
- OrderItem.model.ts  
```
> feat: support recursive file search

- lib/@types/prisma-type-options.ts
Fixes https://github.com/ridafkih/schemix/issues/24
This updates the supported referential actions of `onDelete` and `onUpdate` as described [here](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions)
**There are no tests, so please double check before merging.**
> Update onDelete and onUpdate referential actions

- lib/@types/prisma-type-options.ts
- lib/modules/PrismaModel.ts
- lib/util/options.ts
Fixes https://github.com/ridafkih/schemix/issues/15
Like the `buildCompositeId`, this implements `buildCompositeUnique`.
It accepts either an array of strings (fields), e.g. `["fieldA", "fieldB"]` or an options object, e.g.
```ts
{
fields: ["fieldA", "fieldB"],
map: "field_A_field_B_uniqueness_constraint",  <--- optional
}
```
This will generate
```
@@unique([fieldA, fieldB])
```
and
```
@@unique([fieldA, fieldB], map: "field_A_field_B_uniqueness_constraint")
```
respectively.
**There are no tests, so please double check before merging.**
> Add composite uniqueness

- lib/@types/prisma-type-options.ts
- lib/modules/PrismaEnumField.ts
- lib/util/options.ts
Fixes https://github.com/ridafkih/schemix/issues/21 
This adds the `unique` option to `EnumFieldOptions` and the public `setUnique` method on `PrismaEnumField`. This allows enum fields to be declared as unique via the updated `handleEnumOptions` method.
**There are no tests, so please double check before merging.**
> Allow unique enum fields

- example/mixins/Author.mixin.ts
- example/models/Post.model.ts
- lib/modules/PrismaSchema.ts
Addressed issue #33 by @Daidalos117 in which mixins containing relations did not work. 
This simply moves registration for mixins after enums and models, and introduces the change to the `example/` folder.
> fix: import all mixins after models and enums

- .eslintrc
- lib/util/import.ts
Filters out `.d.ts`, `.d.ts.map`, and `.js.map` files in order to allow for built projects to run! This makes it so that `ts-node` is no longer a hard requirement.
> Built project support

- .eslintrc
- lib/modules/PrismaModel.ts
- lib/modules/PrismaSchema.ts
- lib/util/create.ts
- tests/__snapshots__/index.spec.ts.snap
- tests/modules/__snapshots__/PrismaModel.spec.ts.snap
This pushes the addition of mixins prior to populating the schema to allow them to propagate.
Meant to address #40 by @Daidalos117.
> allow mixins to populate before adding to schema

- examples/programmatic-usage/routes/model.ts
- lib/modules/PrismaModel.ts
- lib/modules/PrismaSchema.ts
- tests/modules/__snapshots__/PrismaModel.spec.ts.snap
This should solve a regression caused by a fix that was released in order to support relations within mixins.
The change is breaking, as it makes the `PrismaModel#toString` function asynchronous. So this will likely be in release `v1.8.0`.  @efreila thank you for raising the issue a la #43.
> fix mixins when interfacing directly with `PrismaModel`

- lib/util/stack.ts
This pull request is intended to fix file paths on Windows machines as per #46.
> match both ticks when getting filename

- lib/modules/PrismaModel.ts
- tests/__snapshots__/index.spec.ts.snap
- tests/modules/__snapshots__/PrismaModel.spec.ts.snap
This should fix the order of the fields when using mixins, I basically wrapped all field setters in setImmediate. This currently passes all tests and outputs the expected schema.
@ridafkih what do you think?
Also, I removed two snapshots that were obsolete.
> fix: keep the fields order same as the source

- lib/typings/prisma-datasource.ts
- tests/modules/PrismaSchema.spec.ts
- tests/modules/__snapshots__/PrismaSchema.spec.ts.snap
As requested by #52, this adds both types and tests for the "extensions" property of `PrismaDataSourceOptions`
> feat: add types to accept "extensions"

- lib/util/blocks.ts
- package.json
- tests/modules/__snapshots__/PrismaSchema.spec.ts.snap
Second pull request meant to address #52 by @KrzysztofZawisla, which removes quotes from "extensions" keys in the key-value blocks 
```ts
const schema = new PrismaSchema(
{
provider: "postgresql",
url: { env: "DATABASE_URL" },
extensions: ["pg_tgrm", "zombodb"],
},
// ...
);
```
From test snapshot, this is the resulting extensions value.
```
datasource database {
provider   = \\"postgresql\\"
url        = env(\\"DATABASE_URL\\")
extensions = [pg_tgrm, zombodb]
}
```
> fix: don't wrap "extensions" in quotes for key-value blocks

- lib/modules/PrismaModel.ts
- lib/typings/prisma-type-options.ts
- lib/util/options.ts
- tests/modules/PrismaModel.spec.ts
- tests/modules/__snapshots__/PrismaModel.spec.ts.snap
Supports the request made in #28 to add decimal precisions as a first-class property of the library.
> include support for decimal precision

- lib/util/blocks.ts
- tests/modules/PrismaSchema.spec.ts
- tests/modules/__snapshots__/PrismaSchema.spec.ts.snap
This addresses #19 by adding an explicit check for the "shadowDatabaseUrl" key and the "env" key in the supplied object.
> fix: allow shadowDatabaseUrl to be set with env key in object

- lib/modules/PrismaEnumField.ts
- lib/modules/PrismaModel.ts
- lib/modules/PrismaRelationalField.ts
- lib/modules/PrismaScalarField.ts
- lib/typings/prisma-type-options.ts
- lib/util/options.ts
- tests/modules/PrismaModel.spec.ts
- tests/modules/__snapshots__/PrismaModel.spec.ts.snap
- tsconfig.json
I wanted to work with `schemix` and `prisma-nestjs-graphql`, saw the corresponding issue#55 and decided to implement this functionality.
If you have any suggestions, feel free to review the code. I am happy to help and adjust the pull request if needed.
Thanks for the great project and Happy Easter!
> add: comment feature

- lib/typings/prisma-datasource.ts
- tests/__snapshots__/index.spec.ts.snap
- tests/index.spec.ts
Fixes an issue referenced in #65, as Prisma has renamed the `referentialIntegrity` attribute name.
> #65 Add 'relationMode' attribute as an option to datasource

- examples/standard-usage/enums/UserRole.enum.ts
- examples/standard-usage/models/User.model.ts
- examples/standard-usage/schema.prisma
- lib/modules/PrismaEnum.ts
- tests/modules/PrismaEnum.spec.ts
- tests/modules/__snapshots__/PrismaEnum.spec.ts.snap
Adds support for @@map on enums the same way it is supported on models.
Resolves #71
> support .map() on enums

- examples/standard-usage/README.md
- examples/standard-usage/models/User.model.ts
- examples/standard-usage/schema.prisma
- lib/modules/PrismaScalarField.ts
- lib/typings/prisma-field.ts
- lib/typings/prisma-type-options.ts
- lib/util/options.ts
- tests/modules/PrismaModel.spec.ts
- tests/modules/__snapshots__/PrismaModel.spec.ts.snap
Noticed the [@ignore](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#ignore) directive is not supported and this is a feature we want to use.
Hopefully everything which needs updating has been done so, please let me know if not.
> Support @ignore Prisma directive
